source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'StringcodeUtils_Example', :exclusive => true do
  pod 'StringcodeUtils', :path => '../'
end

target 'StringcodeUtils_Tests', :exclusive => true do
  pod 'StringcodeUtils', :path => '../'

  pod 'FBSnapshotTestCase'
end
